### ISSUE TITLE
unexpected result

### ISSUE THREAD

**Issue by jonschlinkert** [alferov/is-github-url#2]
I was hoping to use this to validate github URLs for repos and users, but the following returns false:

``` js
isGithubUrl('https://github.com/alferov');
```

which I think a user would expect to be a valid github URL, or is this module only for validating github-git urls? thanks!

**Comment by alferov** [comment]
Oh, it definitely should be there as it's a valid GitHub URL. It would be also nice to provide a set of  different rules to give a user control over validation. 
I'll implement that in the next release.

**Comment by jonschlinkert** [comment]
thanks!
